// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Database;

namespace WebApp.Migrations
{
    [DbContext(typeof(ZeroToHeroContext))]
    [Migration("20180616200150_serie-episodio")]
    partial class serieepisodio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("WebApp.Models.Episodio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("AssistidoEm");

                    b.Property<int>("SerieId");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Episodios");
                });

            modelBuilder.Entity("WebApp.Models.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("AssistidoEm");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100);

                    b.Property<string>("UrlCapa")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Filmes");
                });

            modelBuilder.Entity("WebApp.Models.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Status");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100);

                    b.Property<string>("UrlCapa")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
